version: '3'

services:
  apache:
    image: httpd
    ports:
      - '80:80'
    depends_on:
      - web
  web:
    image: ergofriend/teamproject2
    expose:
      - '8001'
    command: bash -c "gunicorn application.wsgi -b 0.0.0.0:8001"
