version: '3'

services:
  apache:
    image: apache:alpine
    depends_on:
      - web
  web:
    image: ergofriend/teamproject2
    expose:
      - '8001'
    command: bash -c "gunicorn my_docker_project.wsgi -b 0.0.0.0:8001"
